### ISSUE TITLE
Duplicate actions

### ISSUE THREAD

**Issue by thiskbj** [OscarGodson/New-File#3]
Hi there,

Thanks for the awesome script! :) I ran this twice on the install, and ended up getting two copies of the option in the drop-down menu (screenshot attached). Do you know how to delete one of them?

Thanks,
Katie

![screen shot 2013-10-18 at 6 47 34 pm](https://f.cloud.github.com/assets/1014957/1364834/5abcb3b2-3847-11e3-951a-ef486d98d2a6.png)

**Comment by thiskbj** [comment]
Ah, found it! Under System Preferences > Keyboard > Keyboard Shortcuts > Services, the action shows up in the right-side menu. Right click, click 'Show in Finder', delete. 

Thanks again for the script!

**Comment by OscarGodson** [comment]
Sure thing! Let me know if something else comes up.
